server:
  port: 8083

spring:
  application:
    name: reward-service
  datasource:
    url: jdbc:mysql://localhost:3306/rewarddb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: reward-group
    auto-offset-reset: earliest1q
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer