server:
  port: 8761

spring:
  application:
    name: service-registry

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
    peer-eureka-nodes: http://peer1:8761,http://peer2:8761
  eureka:
    instance:
      metadata-map:
        team: backend
        environment: prod
        version: 1.0.0
        zone: in-east
      leaseRenewalIntervalInSeconds: 10  # client sends heartbeat every 10s
      leaseExpirationDurationInSeconds: 30  # Eureka expires if no heartbeat in 30s


management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO