spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customerdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  application:
    name: customer-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: customer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8081




management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true

#  otlp:
#    tracing:
#      endpoint: http://localhost:4317
#  tracing:
#      sampling:
#        probability: 1.0
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG
    com.cust.health: DEBUG
#  pattern:
#    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"