server:
  port: 8085

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
        - AddResponseHeader=X-Gateway, Success
      routes:
        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/notification/**
        - id: customer-service
          uri: http://localhost:8081
          predicates:
            - Path=/customer/**

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info

  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true


otel:
  exporter:
    otlp:
      endpoint: http://localhost:4318


logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG

preference:
  service:
    url: http://localhost:8085

debug: true



